apiVersion: v1
kind: Service
metadata:
  name: sample-grpc
  labels:
    app: sample-grpc
    service: sample-grpc-acc
spec:
  ports:
  - port: 8081
    name: grpc-8081
    appProtocol: grpc
  selector:
    app: sample-grpc
