apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api-v1
  labels:
    app: sample-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-api
      version: v1
  template:
    metadata:
      labels:
        app: sample-api
        version: v1
    spec:
      serviceAccountName: sample-api-acc
      containers:
      - name: sample-api
        image: docker.io/getinfra/sample-api:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 300Mi
          requests:
            memory: 200Mi
            cpu: 50m
        env:
        - name: DOTNET_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: api-cm
              key: dotnet.env
